- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Creating the Container
      docker_container:
        name: 66022770-container            # docker container name
        image: 66022770:latest              # docker image name
        ports:
          - "{{ port }}:80"                 # ใช้ค่าพอร์ตที่ส่งจาก Jenkins
        state: started
        restart: true
